language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - env: COMPILER=g++-5 BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
            - kubuntu-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5

before_script:
  - which $COMPILER
  - mkdir build_tests && cd build_tests
  - cmake .. -Dtstrings_cpp_WITH_TESTS:BOOL=on -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build .
  
script:
  - cd test
  - ctest . -VV -C Debug

branches:
  only:
    - master
    - dev

notifications:
  email: false
